datagen:
    train: 
        pixelwise_center: True
        pixel_mean: 0.25
        pixelwise_normalization: True
        pixel_bounds: (-1000, 400)
        target_size: (96, 96. 96)
    test:
        pixelwise_center: True
        pixel_mean: 0.25
        pixelwise_normalization: True
        pixel_bounds: (-1000, 400)
        target_size: (96, 96. 96)
    flow:
        class_mode: "binary"
        nb_classes: 1
        batch_size: 32
        shuffle: True
        data_augmentation: True
loader:
    train:
        directory: "data/data-science-bowl/npy"
        image_set: "stage1"
        image_format: "npy"
        split: "train"
        test_size: 0.2
        random_state: 42
    test:
        directory: "data/data-science-bowl/npy"
        image_set: "stage1"
        image_format: "npy"
        split: "test"
        test_size: 0.2
        random_state: 42
model:
    compile:
        loss: "binary_crossentropy"
        optimizer: "adam"
        metrics:
            - "accuracy"
    fit_generator:
        samples_per_epoch: 1116
        nb_epoch: 100
        nb_val_samples: 280
        verbose: 1
        max_q_size: 100
